# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'catagories'},
        ),
    ]
